# Build container
FROM golang:bookworm AS build

# Setup environment
RUN mkdir -p /data
WORKDIR /data

# Build the release
COPY . .
RUN make

# Extract the release
RUN mkdir -p /out
RUN cp out/atmosfeed-manager /out/atmosfeed-manager

# Release container
FROM debian:bookworm

# Add certificates
RUN apt update
RUN apt install -y ca-certificates

# Add the release
COPY --from=build /out/atmosfeed-manager /usr/local/bin/atmosfeed-manager

CMD /usr/local/bin/atmosfeed-manager
