// Code generated by scale-signature , DO NOT EDIT.
// output: signature

package signature

import (
	"errors"
	"github.com/loopholelabs/polyglot"
)

var (
	NilDecode   = errors.New("cannot decode into a nil root struct")
	InvalidEnum = errors.New("invalid enum value")
)

type Context struct {
	Include bool
}

func NewContext() *Context {
	return &Context{

		Include: false,
	}
}

func (x *Context) Encode(b *polyglot.Buffer) {
	e := polyglot.Encoder(b)
	if x == nil {
		e.Nil()
	} else {

		e.Bool(x.Include)

	}
}

func DecodeContext(x *Context, b []byte) (*Context, error) {
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return _decodeContext(x, d)
}

func _decodeContext(x *Context, d *polyglot.Decoder) (*Context, error) {
	if d.Nil() {
		return nil, nil
	}

	err, _ := d.Error()
	if err != nil {
		return nil, err
	}

	if x == nil {
		x = NewContext()
	}

	x.Include, err = d.Bool()
	if err != nil {
		return nil, err
	}

	return x, nil
}
