
[package]
name = "questions"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]

signature = { package = "local_classifier_latest_guest", path = "../../pkg/signatures/classifier/rust/guest" }




[profile.release]
opt-level = 3
lto = true
codegen-units = 1
