// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package models

import (
	"time"
)

type Post struct {
	Did       string
	Rkey      string
	CreatedAt time.Time
	Text      string
	Reply     bool
	Langs     []string
	Likes     int32
}
