// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: posts.sql

package models

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
insert into posts (created_at, did, rkey, text, reply, langs, likes)
values ($1, $2, $3, $4, $5, $6, 0)
returning id
`

type CreatePostParams struct {
	CreatedAt time.Time
	Did       string
	Rkey      string
	Text      string
	Reply     bool
	Langs     []string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.CreatedAt,
		arg.Did,
		arg.Rkey,
		arg.Text,
		arg.Reply,
		pq.Array(arg.Langs),
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
